server:
    port: 8102

spring:
    application:
        name: "cards"
    profiles:
      active: "prod"
      
#uncomment for mysql 
#    datasource:
#        url: jdbc:mysql://localhost:3308/cardsdb
#        username: root
#        password: root
#    jpa: 
#        show-sql: true
#    sql:
#      init:
#        mode: always
#
#end of mysql

#for H2
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: ''
    h2:
        console:
            enabled: true
    jpa: 
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
#
## end of H2

    config:
      import: "optional:configserver:http://localhost:8072/"
#    rabbitmq:
#      host: "localhost"
#      port: 5672
#      username: "guest"
#      password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
      
info:
  app:
    name: "cards"
    description: "jayslabs cards microservice"
    version: "1.0.1"
    
logging:
  level:
    jayslabs:
      microservicedemo:
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"