services:
  accounts:
     image: "jaymenorca/accounts:d1"
     container_name: accounts-ms
     ports: 
     - "8082:8082"
     deploy:
       resources:
         limits:
           memory: 700m
     networks:
     - jaymenorca
  loans:
     image: "jaymenorca/loans:d1"
     container_name: loans-ms
     ports: 
     - "8092:8092"
     deploy:
       resources:
         limits:
           memory: 700m
     networks:
     - jaymenorca
  cards:
     image: "jaymenorca/cards:d1"
     container_name: cards-ms
     ports: 
     - "8102:8102"
     deploy:
       resources:
         limits:
           memory: 700m
     networks:
     - jaymenorca
networks:
  jaymenorca:
    driver: "bridge"
