spring:
    application:
        name: "gatewayserver"
    config:
      import: "optional:configserver:http://localhost:8072/"
    cloud:
      gateway:
        discovery:
          locator:
            enabled: false
            lowerCaseServiceId: true
        httpclient:
          connect-timeout: 15000
          response-timeout: 30s
    data:
      redis:
        connect-timeout: 2s
        host: localhost
        port: 6379
        timeout: 1s
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "jayslabs Gateway Server Application"
    version: "1.0.0"
    
logging:
  level:
    jayslabs:
      microservices:
        gatewayserver: DEBUG

resiliency4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
        
         
       
 