build:
  version: "3.33"

cards:
  message: "Cards related local APIs"
  contactDetails:
    name: "User Support - Developer"
    email: "dev@jayslabs.com"
  onCallSupport:
  - (416) 1234567
  - (416) 1234568