spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config"
          search-locations: "file:///C://jay//training//workspaces//eclipse-microservices-springboot-2024//configserver//config"
  
server:
  port: 8072
